
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='amber',
    version='0.1.0',
    description='Search and download high resolution art from museums',
    python_requires='==3.*,>=3.7.0',
    author='GOATS2K',
    author_email='jp@glattetre.com',
    entry_points={"console_scripts": ["amber = amber.commands:cmdgroup"]},
    packages=['amber', 'amber.extractors'],
    package_dir={"": "."},
    package_data={},
    install_requires=['aiodns==2.*,>=2.0.0', 'aiofiles==0.*,>=0.5.0', 'aiohttp==3.*,>=3.6.2', 'appdirs==1.*,>=1.4.4', 'cchardet==2.*,>=2.1.6', 'click==7.*,>=7.1.2', 'colorama==0.*,>=0.4.3', 'halo==0.*,>=0.0.29', 'inquirer==2.*,>=2.6.3', 'pathvalidate==2.*,>=2.3.0', 'termcolor==1.*,>=1.1.0', 'toml==0.*,>=0.10.0'],
    extras_require={"dev": ["black==19.*,>=19.10.0.b0", "dephell==0.*,>=0.8.3", "flake8==3.*,>=3.7.9", "pytest==5.*,>=5.2.0", "rope==0.*,>=0.17.0"]},
)
